### ISSUE TITLE
Setup vim for Rails development

### ISSUE THREAD

**Issue by tmr08c** [tmr08c/dotfiles#21]
- [X] Make it easy to go between files (#26)
  - https://github.com/junegunn/fzf.vim
- [X] Make it easy to run tests (#29)
  - https://github.com/janko/vim-test
- [X] Get [CoC](https://github.com/neoclide/coc.nvim) set up with RoR projects (#39)

Maybe 

- https://github.com/tpope/vim-rails
